name: Validate Muse

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  validate:
    name: Lint, typecheck, and test
    type: custom
    runs_on: linux-medium
    steps:
      - uses: eas/checkout
      - uses: eas/install_node_modules
      - name: Validate
        run: bun run validate
